stages:
- stage: continuous_integration
  displayName: Continuous Integration
  jobs:
  - job: Build
    displayName: Building stage
    steps:
    - script: dotnet --version
      displayName: check version
    - script: dotnet restore
      displayName: Restoring
    - script: dotnet build
      displayName: dotnet building
    - script: dotnet run